// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package sample_package

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SayhiClient is the client API for Sayhi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SayhiClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type sayhiClient struct {
	cc grpc.ClientConnInterface
}

func NewSayhiClient(cc grpc.ClientConnInterface) SayhiClient {
	return &sayhiClient{cc}
}

func (c *sayhiClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/sample_module.sample_package.sayhi/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SayhiServer is the server API for Sayhi service.
// All implementations must embed UnimplementedSayhiServer
// for forward compatibility
type SayhiServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	mustEmbedUnimplementedSayhiServer()
}

// UnimplementedSayhiServer must be embedded to have forward compatible implementations.
type UnimplementedSayhiServer struct {
}

func (UnimplementedSayhiServer) SayHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedSayhiServer) mustEmbedUnimplementedSayhiServer() {}

// UnsafeSayhiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SayhiServer will
// result in compilation errors.
type UnsafeSayhiServer interface {
	mustEmbedUnimplementedSayhiServer()
}

func RegisterSayhiServer(s grpc.ServiceRegistrar, srv SayhiServer) {
	s.RegisterService(&Sayhi_ServiceDesc, srv)
}

func _Sayhi_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SayhiServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sample_module.sample_package.sayhi/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SayhiServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Sayhi_ServiceDesc is the grpc.ServiceDesc for Sayhi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Sayhi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sample_module.sample_package.sayhi",
	HandlerType: (*SayhiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Sayhi_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sayhi.proto",
}
